apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: tqp-volume-test
spec:
  name: unknown
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
  configs:
    retention.ms: "7200000" #2hr
