apiVersion: v1
kind: Pod
metadata:
  name: bqp
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: buffered-quota-client
      image: dedovicnermin/quota-client:1.0.0
      imagePullPolicy: Always
      command:
        - java
        - -cp
        - /app/app.jar
        - io.nermdev.kafka.quota_client.BufferedQuotaProducerSample
      args:
        - /mnt/application/application.properties
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      volumeMounts:
        - mountPath: /mnt/application
          name: appconfig
        - mountPath: /mnt/sslcerts
          name: security
  volumes:
    - name: appconfig
      configMap:
        name: bqp-config
    - name: security
      secret:
        secretName: tls-nermin
