apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: volume-test
spec:
  replicas: 2
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default

