apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: quota.client.qp
  labels:
    principal: unknown
    cscope: kafka
    role: DeveloperWrite
spec:
  role: DeveloperWrite
  principal:
    name: unknown
    type: user
  resourcePatterns:
    - name: qp
      resourceType: Topic
      patternType: PREFIXED
    - name: demo
      resourceType: Topic
      patternType: PREFIXED
  kafkaRestClassRef:
    name: default
