apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - cfrb.yml
  - topic.yml
  - pod.yml

images:
  - name: dedovicnermin/quota-client
    newTag: 1.2.3

configMapGenerator:
  - name: qp-config
    behavior: create
    files:
      - application.properties


patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ConfluentRolebinding
    patch: |-
      - op: replace
        path: /metadata/labels/principal
        value: dev1
      - op: replace
        path: /spec/principal/name
        value: dev1
  - target:
      version: v1
      kind: Pod
    patch: |-
      - op: replace
        path: /spec/volumes/1/secret/secretName
        value: tls-dev1

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KafkaTopic
    patch: |-
      - op: replace
        path: /spec/name
        value: demo.topic1
      - op: replace
        path: /spec/replicas
        value: 1