apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: qp-volume-test
spec:
  name: demo.topic1
  replicas: 2
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
  configs:
    retention.ms: "9200000" 
