apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - cfrb.yml
  - pod.yml

images:
  - name: dedovicnermin/quota-client
    newTag: 1.2.4

configMapGenerator:
  - name: qc-config
    behavior: create
    files:
      - application.properties

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ConfluentRolebinding
    patch: |-
      - op: replace
        path: /metadata/labels/principal
        value: dev2
      - op: replace
        path: /spec/principal/name
        value: dev2
  - target:
      version: v1
      kind: Pod
    patch: |-
      - op: replace
        path: /spec/volumes/1/secret/secretName
        value: tls-dev2

