apiVersion: v1
kind: Pod
metadata:
  name: qac
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: quota-client
      image: dedovicnermin/quota-client
      imagePullPolicy: Always
      command:
        - java
        - -cp
        - /app/app.jar
        - io.nermdev.kafka.quota_client.clients.consumer.QuotaAvroConsumer
      args:
        - /mnt/application/application.properties
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      volumeMounts:
        - mountPath: /mnt/application
          name: appconfig
        - mountPath: /mnt/sslcerts
          name: security
  volumes:
    - name: appconfig
      configMap:
        name: qac-config
    - name: security
      secret:
        secretName: ???
